# Generated by Django 3.0.5 on 2021-01-07 08:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('book', models.FileField(blank=True, upload_to='books')),
                ('cover', models.ImageField(blank=True, upload_to='cover')),
                ('grade', models.CharField(max_length=3)),
                ('branch', models.CharField(choices=[('Natural Science', 'Natural Science'), ('Social Science', 'Social Science'), ('other', 'other')], max_length=30)),
                ('subject', models.CharField(choices=[('biology', 'biology'), ('chemistry', 'chemistry'), ('business', 'business'), ('english', 'english'), ('civic', 'civic')], max_length=30)),
                ('date', models.DateTimeField(verbose_name=django.utils.timezone.now)),
            ],
        ),
    ]
